services:
  - type: web
    name: stockzeno-wms
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_URL
        fromDatabase:
          name: stockzeno-db
          property: connectionString
      - key: DB_USER
        fromDatabase:
          name: stockzeno-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: stockzeno-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_BASE_URL
        value: https://stockzeno.vercel.app
      - key: CORS_ALLOWED_ORIGINS
        value: https://stockzeno.vercel.app


databases:
  - name: stockzeno-db
    databaseName: stockzeno
    user: stockzeno
    plan: free
